### ISSUE TITLE
Some labels not getting bundled

### ISSUE THREAD

**Issue by txie1993** [teresa-ou/inboxy#18]
Hello,

I have a filter for review requests in my work email, and then another filter within that specifically labels review requests I am tagged on.

General review requests are set to skip my inbox, but review requests to me appear in my inbox starred and marked as important. These are all appear like so in my inbox rather than being bundled, though other labels in my inbox are getting bundled normally.

<img width="153" alt="Screen Shot 2020-04-06 at 11 30 52 AM" src="https://user-images.githubusercontent.com/12758631/78592554-1d942980-77fa-11ea-9b12-a4c2f7e6c42e.png">

Thanks! This extension is much appreciated.

**Comment by teresa-ou** [comment]
If the emails are starred, then they won't get bundled. Starring an email is like pinning an email in Google Inbox, so a starred message will appear outside of the bundle. Would it work for your use case if you turn off the automatic starring of those emails?

A separate but related issue, is that perhaps the star icon should be replaced with a pin icon, so that the new functionality of stars is clearer.

**Comment by txie1993** [comment]
Thanks for the reply. Unstarring messages with the label worked and they are now bundled.

**Comment by benoror** [comment]
Hi! Please retry on **Inbundly**. Empty label-chip titles were fixed (v3.1.2), and starred-outside-bundle is configurable. If a specific nested review label still never bundles, open a bug with the label path.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Issues: https://github.com/benoror/inbundly/issues/new
