### ISSUE TITLE
Enhancement request: make inboxy compatible with Simplify

### ISSUE THREAD

**Issue by teresa-ou** [teresa-ou/inboxy#19]

**Comment by jakezien** [comment]
I'm the commenter from Reddit; thanks for opening this! The main collision I'm seeing is that Simplify removes the grey backgrounds from all rows of the inbox, and Inboxy seems to put them back for bundles and unread messages.

Simplify without Inboxy:
![simplify](https://user-images.githubusercontent.com/1486983/79004067-fc954680-7b21-11ea-84c4-eea3683fc947.png)

Simplify with Inboxy:
![simplify+inboxy](https://user-images.githubusercontent.com/1486983/79004081-01f29100-7b22-11ea-9854-381bd47bedd1.png)

Thanks again for your lifesaving work on this extension!

**Comment by teresa-ou** [comment]
Thanks for describing the issue! I should be able to release a fix for this soon.

**Comment by teresa-ou** [comment]
This should be fixed in v1.4.0

**Comment by jakezien** [comment]
Thank you!

**Comment by bgiesing** [comment]
![image](https://user-images.githubusercontent.com/7895463/80450062-5057ac00-88e6-11ea-828e-c78dbf39e131.png)

When using Simplify's "Keep search minimized when not in use" setting, Inboxy's Pinned toggle overlaps with the Settings icon

**Comment by teresa-ou** [comment]
@bgiesing I think this is caused by the presence of the icon with the 4 horizontal lines -- could you let me know what that feature is?

**Comment by bgiesing** [comment]
@teresa-ou That's the Reading Pane feature in Gmail under Settings > Inbox > Enable Reading Pane

**Comment by bgiesing** [comment]
Actually now that I'm thinking about it, it's actually somewhat broken in other ways because the Reading Pane also so this likely should be a separate issue.

- The Bundle styling seems to break slightly cause it being shown in the slim sidebar of Right Split
![image](https://user-images.githubusercontent.com/7895463/80551992-e3e2b880-898a-11ea-935e-a2f2178964d1.png)
- When clicking archive on an email, it loads up the next email into the pane in normal list order, not the next email in that bundle only

**Comment by teresa-ou** [comment]
I opened a separate issue for the pinned toggle here: https://github.com/teresa-ou/inboxy/issues/27

In general, I wouldn't be surprised if there are a number of problems when using the reading pane, since I haven't really tested inboxy with the reading pane.

**Comment by benoror** [comment]
Hi! Simplify compatibility is best-effort only. **Inbundly** is the active fork if you want current Gmail support. Please file concrete layout bugs with screenshots rather than a blanket compat matrix.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Issues: https://github.com/benoror/inbundly/issues/new
