### ISSUE TITLE
Feature Request: Show the entire inbox below bundles

### ISSUE THREAD

**Issue by nikonikolov** [teresa-ou/inboxy#41]
In the inbox view I can currently see only emails which correspond to a bundle. However if an email was sent say 2 months ago, it's not visible. Can you please make the entire inbox appear in the red region on the image such that users can easily scroll through. Thanks a lot for this extension, great work!

![image](https://user-images.githubusercontent.com/11044035/83977320-a8c39580-a8f7-11ea-8c32-74916afa12a9.png)

**Comment by teresa-ou** [comment]
Emails that don't belong to a bundle should appear in their own row. 

Based on the screenshot above, I would guess that many of the emails are filed under "Updates" -- it has at least 25 of the 50 total emails shown on this page. In addition, although "Updates" appears under "Today", it also includes emails from before today. (It shows up under today because the most recent email in the bundle arrived today.)

**Comment by nikonikolov** [comment]
Thanks, looks like that's correct. Increasing the limit to 100 emails per page also made it look more natural.
