### ISSUE TITLE
Feature Request: Configurable option for how many messages are displayed in a bundle

### ISSUE THREAD

**Issue by nikonikolov** [teresa-ou/inboxy#42]
Currently when I expand a bundle, I can see only very few of the messages which belong to the bundle, like 4-5. This is rather prohibitive for a bundle which has a high frequency of emails. Can you increase the number of emails shown or maybe better, add a user-configurable option how many emails are shown when the bundle is expanded.

**Comment by teresa-ou** [comment]
Since inboxy only makes visual changes to what Gmail already displays on the page, the maximum number of emails that can be shown in a bundle is limited by Gmail's number of conversations per page. If you haven't already, I recommend changing your Gmail settings to show 100 conversations per page (the maximum number), to increase the number of emails shown per bundle. 

I think this feature request is the same as #1, so I'm closing this for now.

**Comment by vtexperts** [comment]
@nikonikolov - try this: https://github.com/vtexperts/gmail-increase-maximum-page-size
I built it so increase limit to 200.
