### ISSUE TITLE
Bundles not appearing

### ISSUE THREAD

**Issue by cgonz313** [teresa-ou/inboxy#55]
It doesn't appear the bundles are happening happening anymore as I'm back to see the default list of emails.

**Comment by teresa-ou** [comment]
Have you seen the discussion in #20? There are some Gmail settings that inboxy is not compatible with, most notably non-default inbox types. Let me know if the info in that link doesn't help, or if you did see bundles previously and now aren't seeing them (without any changes to your Gmail settings).

**Comment by cgonz313** [comment]
Yeah, I've seen it but I have them set up exactly how it's described. 

It doesn't work in both Firefox and Chrome.

**Comment by teresa-ou** [comment]
One more thing that's not mentioned in that thread -- any chance you're on a workplace computer? Some companies block extensions from working on sensitive websites like email.

If you're not on a workplace computer,
- Do you see any visual changes to gmail? For example, the archive button should appear as a checkmark, and unread emails should be grey instead of white if you're using a light color scheme.
- Do you see any errors in the [developer console](https://developers.google.com/web/tools/chrome-devtools/open#console) upon loading Gmail? You can open the developer console with Command+Option+J (Mac) or Control+Shift+J (other operating systems).

**Comment by cgonz313** [comment]
The console logs appear to be showing the same errors whether Inboxy is
enabled or not.

I do see the visual changes only when the Inbox is enabled.

I even tried viewing on an alternate account that's pretty default and I
created a test label and it still didn't work.

**Comment by teresa-ou** [comment]
I uploaded a new version for Chrome, v1.5.4, which will print debug information to the console. Your browser will automatically install the update in the next few days or so. 

Could you send me the logs after you have v1.5.4? It will look like this:
![image](https://user-images.githubusercontent.com/5694027/89130200-ceb08500-d4b7-11ea-9c7d-9493cec57139.png)

**Comment by cgonz313** [comment]
The update is live and the console log looks identical for it.  I even
tried on a minty fresh version of chrome with no other extensions installed
as well as a different gmail I set up for my dog (heh) and it's still not
working.

[image: Screen Shot 2020-08-03 at 1.28.25 PM.png]

**Comment by cgonz313** [comment]
OK, well.  In a weird twist, it seems to be working again.

I've got nothing now. haha

**Comment by teresa-ou** [comment]
That's strange, but I'm glad it's working for you! Closing this issue.
