### ISSUE TITLE
Css settings

### ISSUE THREAD

**Issue by JoeriTheGreat** [teresa-ou/inboxy#62]
Hi,

I have changed the following css code with stylus:
```
.time-row{
    display:none;
}

html.inboxy .bundle-row.zA.yO.visible, html.inboxy .bundle-row.zA.zE.visible {
    background-color: rgb(232, 234, 237)!important;
}

html.inboxy .bundle-row.visible .xY.yX {
    margin-left: 47px;
}
```

I use inbox reburn theme with everything disabled except avatar logo's to get the right look and feel that inbox had.

**Comment by teresa-ou** [comment]
Thanks for sharing! 

inboxy is purposefully unopinionated in its appearance. That is, it tries to keep any styling changes minimal and consistent with Gmail. 

Some users may prefer the appearance of Google Inbox, so your solution sounds great for that. Other users may prefer [Simplify Gmail](https://simpl.fyi/), and you can use both Simplify and inboxy together. Or for those who like the look of Gmail, they can use inboxy by itself. 

I don't plan to add capability for custom css, since that extends beyond the scope of inboxy's goals (see #39 for more details).
